log:
  level: WARN # INFO

global:
  checkNewVersion: true
  sendAnonymousUsage: false

accessLog:
  filePath: /log/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "200"
      - "300-302"
      - "400-499"
    retryAttempts: true
    minDuration: 10

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false
    network: traefik-proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: 4clop@gmail.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

  letsencrypt-test: # for testing and development
    acme:
      email: 4clop@gmail.com
      storage: acme.json
      keyType: EC384
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" # for testing
      httpChallenge:
        entryPoint: web