<?php
include_once("backend/allfunctions.php");
$extratitle = "Rules - ";
include("header.php");
echo <<<EOFORM
&gt;CLOP has only four major rules:<br/><br/>
<b>1.</b> <font size="4">One person, one account.</font><br/>
The cooperative aspects of this game and the vagaries of the market can be frustrating, even maddening.
You will probably be tempted to make more accounts to get the things you need.
If you succumb to these temptations, you <strong>WILL</strong> be banned. No exceptions. Get some friends instead. Or take over other nations through war.</br> If you say that it's your brother or
your cousin or whoever sharing the computer or home network, <b>the admin will not believe you</b>. If there really are two of you, other players can help you prove it through Skype.
And if you've got someone who plays &gt;CLOP coming over to your house, <b>warn the admin first!</b>
<br/>
You can play on a public network with other >CLOP players, but don't create new accounts on a public computer. This includes coffee shop wi-fi networks, school networks, and libraries.
Unless people have connected from residential IPs before, I can't know whether they're actually multiple people or your imaginary friends.
If there's any situation in which there's more than one account generated by one outward-facing IP address,
it's banland for the IP and possibly deletion for the accounts.<br/>
<br/>
And no, don't go wardriving around your neighborhood to make accounts and play them at school.
Don't make alternate accounts through proxies, the banlist is long enough as it is. The admin sees the same lists you do. TOR won't work either.<br/>
<br/>
Whatever clever scheme you've devised, it's already been thought of.
"But if I buy from others and resell to my main, the admin will never-" No, the admin will see it. "I'll just sell-" No, the admin will see it.
"If I say that-" The admin doesn't want to hear your excuses. "Maybe if I make multiples and buy from someone I hate, the admin will ban that-" No, the admin's not that stupid.
"Well, if I make one account at school and the other at home-" The admin will figure it out sooner or later, and the admin is a fucking Nazi about this shit. <b>Don't make multiple accounts.</b><br/>
<br/>
<b>No account sharing between >CLOP players.</b> Two people on one account is fine, two people sharing two accounts is not. Sharing passwords is a bad idea anyway. "I was just taking care of it
for..." Banned. "It's my brother's account, I just log in to..." Banned. "I logged on as him so I could..." Banned.<br/><br/>
<b>2.</b> No computer shenanigans.<br/>
No password theft, no spamming, no exploiting if you find one (in which case, tell the admin what it is).<br/>
Donators can use HTML in nation and alliance descriptions.</font>
However, any XSS attack, fake page, browser-paralyzing attack, or other trickery will result in a ban and account deletion. Don't throw your money away.<br/>
No juvenile interface shit like horizontal scroll, excessive vertical scroll, browser pony overkill, autoplaying annoying music, or invisible text, either.
<br/><br/>
<b>3.</b> Leave real life out of it.<br/>
If you're mad enough to dox someone over a browser pony game, it's time to re-evaluate your life's priorities.<br/><br/>
&gt;CLOP is chock-full of 4channers and other weirdos whose idea of a good time involves a small horse and a tube of KY.
<b>Do not give any of these people your personal information, ever, especially if you actually own a stable.</b><br/><br/>
<b>4.</b> You may not sacrifice your last nation.<br/>
Building a nation to be taken over by another player is banned. Buying and selling a player's last nation is banned. <b>Giving anyone anything in recompense for taking his last nation is banned</b>,
whether you do it yourself or your friends do it for you.<br/><br/>
Intentionally overloading your nation to give or lend the products to another player, knowing it will lead to the destruction of your nation, is banned.
You may not prevent your nation from being taken over by burning it down or making it unviable, and you are not allowed to destroy your own buildings
to spite an attacker as this is a crime against equinity.
(Leaving nothing but a couple days' worth of upkeep for your ponies to survive on is okay.)<br/><br/>
<b>Other than these, there are no rules.</b> Take over the economy, manipulate the market, lie extravagantly, gang up on whoever you want.
EOFORM;
include("footer.php");
?>